apiVersion: v1
kind: Secret
metadata:
  name: ms-brigadas-secret
  namespace: muni-valle-sol
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://ep-orange-bar-an1823ou-pooler.c-6.us-east-1.aws.neon.tech/ms-brigadas?sslmode=require&channelBinding=require"
  DB_USERNAME: "neondb_owner"
  DB_PASSWORD: "npg_sK8pYXDgEd3I"